### PR TITLE
new additional collections

### PR DESCRIPTION
**Pull request by g-spawnPL**
could someone please add a new collection of lego games?

### CODE REVIEW

**Comment by g-spawnPL** [comment]
Hi,
another missing system...
[vc4000.zip](https://github.com/CkauNui/ckau-book/files/8614114/vc4000.zip)

Preview:
vc4000

**Comment by Lendersmark** [comment]
> Hi, another missing system... [vc4000.zip](https://github.com/CkauNui/ckau-book/files/8614114/vc4000.zip)
> 
> Preview: vc4000

Thank you @g-spawnPL I will add it to my repo very soon.

Also: I use GIMP as you do.
So I can convert your XCF source files to PSD (I'd like to make a single .zip package file with all my PSDs and yours, to share it with @CkauNui so he can evaluate what to keep, what to modify, improve, etc...)

But in your source XCF files the background is flattened together with other elements (TV, console, etc.)
So I can't make dark versions from them. Can you provide your XCF files with a separate background layer?

**Comment by g-spawnPL** [comment]
> Thank you @g-spawnPL I will add it to my repo very soon. I'm adding as much as DARKFUL versions of the new systems as I can - I can do it if I find the right PSD source file.
> 
> I use GIMP as you do: so I can convert your XCF source files to PSD (after that, I'd like to make a single .zip package file with all my PSDs and yours, to share it with @CkauNui so he can evaluate what to keep, what to modify, improve, etc...)
> 
> But in your source XCF files the background is flattened together with other elements (TV, console, etc.) So I can't make dark versions from them. Can you provide your XCF files with a separate background layer?

Unfortunately, I do not have and never have had the source files and was based on existing pngs that I redesigned.
If you can share all the source PSD's I will try to rework what I have created so far because it really does not look good on a 4K TV :P

**Comment by Lendersmark** [comment]
> > Thank you @g-spawnPL I will add it to my repo very soon. I'm adding as much as DARKFUL versions of the new systems as I can - I can do it if I find the right PSD source file.
> > I use GIMP as you do: so I can convert your XCF source files to PSD (after that, I'd like to make a single .zip package file with all my PSDs and yours, to share it with @CkauNui so he can evaluate what to keep, what to modify, improve, etc...)
> > But in your source XCF files the background is flattened together with other elements (TV, console, etc.) So I can't make dark versions from them. Can you provide your XCF files with a separate background layer?
> 
> Unfortunately, I do not have and never have had the source files and was based on existing pngs that I redesigned. If you can share all the source PSD's I will try to rework what I have created so far because it really does not look good on a 4K TV :P

Here you go:
https://drive.google.com/drive/folders/1Ewz5_vGKcUlE6rizpJ3UvdnZFxONemIa?usp=sharing

If you could rework your artworks and also make the dark version (just replace the background color with black #000000 and it's done) it would be great.

Also, re-factoring all the artworks in 4k would be great for future versions.
(Viking PSDs, from his Colorful Theme for Bigbox, are originally in 4k)

**Comment by Lendersmark** [comment]
Hey @g-spawnPL I noticed you have put your new PSDs on the drive folder! So cool.
Please add me on Discord so we can chat without flooding Github :) 
Lendersmark#4205

**Comment by g-spawnPL** [comment]
HI

Ok my discord: g-spawn#3024

Wysłane z aplikacji Poczta dla systemu Windows 

Od: Lendersmark
Wysłano: czwartek, 12 maja 2022 21:08
Do: CkauNui/ckau-book
DW: g-spawnPL; Mention
Temat: Re: [CkauNui/ckau-book] new additional collections (PR #17)

Hey @g-spawnPL I noticed you have put your new PSDs on the drive folder! So cool.
Please add me on Discord so we can chat without flooding Github :)
Lendersmark#4205

**Comment by CkauNui** [comment]
Hi, thank you very much for your help in creating the theme, I'll look into everything a bit later. I need a little more time to finish my business.

**Comment by Lendersmark** [comment]
Ok don't worry :blush:
We're about to release version 1.2 that will support _all_ of Batocera v33 & Retrobat v4.0.2 systems.
Let's keep in touch here or in Discord, when you'll have time to look into it.

**Comment by CkauNui** [comment]
Close, please send new Pull request in **dev** branch

**Pull request closed without merging**
